name: Updated documentation

on:
  release:
    types: ['released']

  workflow_dispatch:

env:
  SPHINXWORKING: True

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup conda env
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/docs_env.yaml
          environment-name: docs
          condarc: |
            channels:
              - uibcdf
              - conda-forge
              - ambermd
              - defaults
            channel_priority: strict
          create-args: >-
            python=3.11

      - name: Info conda
        shell: bash -l {0}
        run: |
          micromamba activate docs
          micromamba info
          micromamba list

      - name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps

      - name: Test import module
        shell: bash -l {0}
        run: |
          echo "::group::Importing module from home directory"
          cd
          pwd
          echo 'import molsysmt; print("Version of the package: {}".format(molsysmt.__version__))' | python
          echo "::endgroup::"

      - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v2.1.0

