name: Sphinx docs to gh-pages

on:
  release:
    types: ['released']

  workflow_dispatch:

env:
  SPHINXWORKING: True

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a

      - name: Setup GNU Fortran
        uses: modflowpy/install-gfortran-action@v1 # https://github.com/modflowpy/install-gfortran-action

      - name: Make conda environment
        uses: conda-incubator/setup-miniconda@v2    # https://github.com/conda-incubator/setup-miniconda
        with:
          python-version: 3.9
          environment-file: devtools/conda-envs/docs_env.yaml
          #mamba-version: "*"
          #use-mamba: true
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
          activate-environment: test

          #- name: Setup conda env
          #  uses: mamba-org/provision-with-micromamba@main
          #  with:
          #    environment-file: devtools/conda-envs/docs_env.yaml
          #    environment-name: docs
          #    channels: uibcdf, conda-forge, ambermd, defaults

          #    extra-specs: |
          #      python=="3.9"

      - name: Install package

        shell: bash -l {0}
        run: |
          python setup.py develop

          #- name: Info conda
          #  shell: bash -l {0}
          #  run: |
          #    micromamba info
          #    micromamba list

      - name: Info conda
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Test import module
        shell: bash -l {0}
        run: |
          echo "::group::Importing module from home directory"
          cd
          pwd
          echo 'import molsysmt; print("Version of the package: {}".format(molsysmt.__version__))' | python
          echo "::endgroup::"

      - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.1.0

